"""Add bank_connections table for multiple bank support

Revision ID: 9ab2b0b9d566
Revises: 001_initial
Create Date: 2026-01-07 16:56:26.569173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab2b0b9d566'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create TransactionType enum if it doesn't exist
    op.execute("CREATE TYPE transactiontype AS ENUM ('credit', 'debit')")

    # Create bank_connections table
    op.create_table('bank_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Add bank_connection_id column as nullable first (since no data exists to link to)
    op.add_column('accounts', sa.Column('bank_connection_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_accounts_bank_connection_id'), 'accounts', ['bank_connection_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'bank_connections', ['bank_connection_id'], ['id'], ondelete='CASCADE')

    # Alter transaction_type column to use enum
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('credit', 'debit', name='transactiontype'),
               existing_nullable=False,
               postgresql_using='transaction_type::transactiontype')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum('credit', 'debit', name='transactiontype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_bank_connection_id'), table_name='accounts')
    op.drop_column('accounts', 'bank_connection_id')
    op.drop_table('bank_connections')
    # ### end Alembic commands ###
